name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Test the workflow
        shell: bash
        run: |
          echo "Hello world"
          
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: godwindev.jumpingcrab.com
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script_path: ./deploy.sh
