name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Test the workflow
        shell: bash
        run: |
          echo "Hello world"
